version: "3"

services:
    db:
      image: db-gpe:dev
      ports:
        - "4406:3306"
      environment:
        MYSQL_USER: "gpe_user"
        MYSQL_PASSWORD: "jesuislepassword"
        MYSQL_DATABASE: "gpeDb"
        MYSQL_ROOT_PASSWORD: "root"
      networks:
        - gpe-net

    fast-api:
      image: fast-api-gpe:dev
      ports:
        - "8081:8000"
      environment:
        - "DB_USER=gpe_user"
        - "DB_PASSWORD=jesuislepassword"
        - "DB_URL=db"
        - "DB_PORT=4406"
        - "DB_NAME=gpeDb"
      volumes:
        - ./api:/app/
      networks:
        - gpe-net

networks:
  gpe-net:

