version: "3"

services:
    fast-api:
      image: fast-api-gpe:dev
      command:  uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
      depends_on:
        - db
      ports:
        - "8081:8000"
      volumes:
        - ./api:/app/
      networks:
        - gpe-net
        
    db:
      image: db-gpe:dev
      ports:
        - "3306:3306"
      environment:
        - "MARIADB_DATABASE=gpeDb"
        - "MARIADB_ROOT_PASSWORD=root"
      volumes:
        - ./databases/data:/var/lib/mysql
      networks:
        - gpe-net
      

networks:
  gpe-net:

